name: "VCPKG F3D CI"
description: "VCPKG F3D CI"
inputs:
  lfs_sha:
    description: "Cache LFS sha"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check required inputs
      shell: bash
      run: |
        [[ "${{ inputs.lfs_sha }}" ]] || { echo "lfs_sha input is empty" ; exit 1; }
        [[ "${{ inputs.vtk_version }}" ]] || { echo "vtk_version input is empty" ; exit 1; }

    - name: Recover LFS Data
      uses: f3d-app/lfs-data-cache-action@v1
      with:
        type: "consumer"
        lfs_sha: ${{inputs.lfs_sha}}
        cache_postfix: cache-0

    - name: Setup Directories
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        mkdir build

    - name: Configure
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: >
        cmake ../source --preset=vcpkg

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build .
